[build]

# Pi 2/3/4
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# (Optional) Set default target for cargo build
# target = "armv7-unknown-linux-gnueabihf"
# rustflags = ["-C", "linker=arm-none-linux-gnueabihf-gcc"]
